### ISSUE TITLE
Exception STM32CubeIDE

### ISSUE THREAD

**Issue by FraWeg** [sgnes/elf_addr_dict#1]
Great work!

Exception with elf files build with STM32CubeIDE 1.3.0.

[STM32CubeIDE_ELF.zip](https://github.com/sgnes/pyelfwrapper/files/5654105/STM32CubeIDE_ELF.zip)

Traceback (most recent call last):
…
packages\elfwrapper\elf_wrapper.py", line 215, in _process_variable
    self.variables_dict[at_name] = attrs
UnboundLocalError: local variable 'at_name' referenced before assignment

Thanks!

**Comment by sgnes** [comment]
Sorry for the late reply,  I don't know why it generate a elf file like this, I'm not a expert of DWARF2, a simple implementation is to use its die.offset as name, at least this script still can work,thanks.
