### ISSUE TITLE
STM32CubeIDE DW_TAG_structure_type

### ISSUE THREAD

**Issue by FraWeg** [sgnes/elf_addr_dict#2]
Problem with 
`self._re_pattern = re.compile(r'DW_OP_plus_uconst:\s+(\d+)')`
more precisely
```
        off = re.findall(self._re_pattern,
                         root_struct[mem_base].DW_AT_data_member_location)[0]
```

DW_AT_data_member_location doesn't include DW_OP_plus_uconst:

    _|DW_AT_data_member_location:  AttributeValue(name='DW_AT_data_member_location', form='DW_FORM_data1', value=2, raw_value=2, offset=322083)_

Thanks!

**Comment by sgnes** [comment]
thanks for the feedback, would be greate if you could share with me a code sample or a elf file, so that I can check it on my side, thanks.

**Comment by sgnes** [comment]
@FraWeg please check with the latest code, it should fix the issue, sorry for the late response.
